import {test,expect} from '@playwright/test'
import {login,setup,navigate} from './helpers'

test('budget groups, saved layout, trend values, palette and live system theme',async({page},info)=>{
 await page.emulateMedia({colorScheme:'dark'})
 await page.goto('./')
 await login(page,`budget-${info.project.name}@example.test`)
 await setup(page)
 await expect(page.getByTestId('budget-savings')).toContainText('—')
 await page.getByRole('button',{name:'Afficher les explications : Répartition du budget'}).click()
 await expect(page.getByRole('dialog')).toContainText('20 %')
 await page.getByRole('button',{name:'Fermer',exact:true}).click()
 await navigate(page,'Catégories')
 for(const name of ['Charges','Épargne','Plaisirs']) await expect(page.getByLabel(`Groupe de ${name}`,{exact:true})).toBeVisible()
 await page.getByPlaceholder('Nouvelle catégorie...').fill('Abonnement')
 await page.getByRole('button',{name:'Ajouter la catégorie',exact:true}).click()
 await page.getByLabel('Groupe de Abonnement').selectOption('charges')
 await navigate(page,'Comptes')
 await expect(page.getByRole('button',{name:'Bleu',exact:true})).toBeVisible()
 await page.getByLabel('Nom du compte').fill('Alpha')
 await page.getByRole('button',{name:'Bleu',exact:true}).click()
 await page.getByRole('main').getByRole('button',{name:'Ajouter',exact:true}).click()
 await expect(page.getByLabel('Nom du compte')).toHaveValue('')
 for (const [index, [type, amount, category]] of [['Entrée','1000','Charges'],['Sortie','500','Charges'],['Sortie','200','Épargne'],['Sortie','300','Plaisirs']].entries()) {
   await navigate(page,'Ajouter')
   await page.getByRole('button',{name:type,exact:true}).click()
   await page.getByLabel('Montant (€)').fill(amount)
   await page.getByLabel('Catégorie',{exact:true}).selectOption({label:category})
   await page.getByLabel('Date',{exact:true}).fill(`2001-01-0${index+1}`)
   await page.getByRole('button',{name:/Enregistrer/}).click()
   await expect(page.getByRole('heading',{name:'Historique',exact:true})).toBeVisible()
 }
 await navigate(page,'Dashboard')
 await page.getByRole('combobox').selectOption('all')
 for (const group of ['charges','savings','fun']) await expect(page.getByTestId(`budget-${group}`)).toHaveClass(/text-negative/)
 await page.screenshot({path:info.outputPath('budget.png'),fullPage:true})
 await navigate(page,'Paramètres')
 await page.getByRole('button',{name:'Monter Consommation'}).click()
 await page.getByLabel('Afficher les valeurs de tendance').check()
 await page.getByRole('button',{name:'Activer le mode système'}).click()
 await page.emulateMedia({colorScheme:'light'})
 await expect(page.locator('html')).toHaveAttribute('data-theme','light')
 await navigate(page,'Dashboard')
 await expect(page.locator('[aria-label="Valeurs de tendance"]')).toContainText('/mois')
 await page.emulateMedia({colorScheme:'dark'})
 await expect(page.locator('html')).toHaveAttribute('data-theme','dark')
 await page.reload()
 await expect(page.getByRole('heading',{name:'Dashboard'})).toBeVisible()
 await expect(page.locator('.grid > div').first()).toContainText('Consommation')
 await navigate(page,'Paramètres')
 await expect(page.getByLabel('Afficher les valeurs de tendance')).toBeChecked()
 await navigate(page,'Catégories')
 await expect(page.getByLabel('Groupe de Abonnement')).toHaveValue('charges')
})
