import { test, expect } from '@playwright/test'
import { setup, login, logout } from './helpers'

test('compte e-mail vérifié, reconnexion et réinitialisation conservent le coffre', async ({ page, request }, info) => {
  const email = `email-${info.project.name}@example.test`
  await page.goto('./')
  await page.getByRole('button', { name: 'Créer un compte', exact: true }).click()
  await page.getByLabel('Adresse e-mail').fill(email)
  await page.getByLabel('Mot de passe', { exact: true }).fill('mot de passe fictif')
  await page.getByLabel('Confirmer le mot de passe').fill('différent')
  await page.getByRole('button', { name: 'Créer mon compte' }).click()
  await expect(page.getByRole('alert')).toContainText('ne correspondent pas')
  await page.getByLabel('Confirmer le mot de passe').fill('mot de passe fictif')
  await page.getByRole('button', { name: 'Créer mon compte' }).click()
  await expect(page.getByRole('heading', { name: 'Vérifie ton adresse e-mail' })).toBeVisible()
  await page.getByRole('button', { name: 'J’ai vérifié mon adresse' }).click()
  await expect(page.getByRole('status')).toContainText('pas encore vérifiée')
  const codes = async () => (await (await request.get('http://127.0.0.1:9099/emulator/v1/projects/demo-mes-comptes-v2/oobCodes')).json()).oobCodes.filter(c => c.email === email)
  await expect.poll(async () => (await codes()).length).toBeGreaterThan(0)
  const verify = (await codes()).find(c => c.requestType === 'VERIFY_EMAIL')
  await page.evaluate(async code => {
    const { applyActionCode } = await import('/mes-comptes/node_modules/.vite/deps/firebase_auth.js')
    const { auth } = await import('/mes-comptes/src/firebase.js')
    await applyActionCode(auth, code)
  }, verify.oobCode)
  await page.getByRole('button', { name: 'J’ai vérifié mon adresse' }).click()
  await setup(page)
  const uid = await page.evaluate(async () => (await import('/mes-comptes/src/firebase.js')).auth.currentUser.uid)
  await logout(page)
  await page.getByRole('button', { name: 'Mot de passe oublié', exact: true }).click()
  await page.getByLabel('Adresse e-mail').fill(email)
  await page.getByRole('button', { name: 'Envoyer le lien' }).click()
  await expect(page.getByRole('status')).toContainText('Si un compte correspond')
  const reset = (await codes()).find(c => c.requestType === 'PASSWORD_RESET')
  await page.evaluate(async code => {
    const { confirmPasswordReset } = await import('/mes-comptes/node_modules/.vite/deps/firebase_auth.js')
    const { auth } = await import('/mes-comptes/src/firebase.js')
    await confirmPasswordReset(auth, code, 'nouveau mot de passe fictif')
  }, reset.oobCode)
  await page.getByRole('button', { name: 'Retour à la connexion' }).click()
  await page.getByLabel('Mot de passe', { exact: true }).fill('nouveau mot de passe fictif')
  await page.getByRole('button', { name: 'Se connecter', exact: true }).click()
  await expect(page.getByLabel('Passphrase', { exact: true })).toBeVisible()
  expect(await page.evaluate(async () => (await import('/mes-comptes/src/firebase.js')).auth.currentUser.uid)).toBe(uid)
  await page.getByLabel('Passphrase', { exact: true }).fill('passphrase fictive')
  await page.getByRole('button', { name: '🔓 Déverrouiller', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Dashboard' })).toBeVisible()
})


test('un compte Google retrouve le même uid après ajout du mot de passe par récupération', async ({ page, request }, info) => {
  const email = `google-email-${info.project.name}@example.test`
  await page.goto('./')
  await login(page, email)
  await setup(page)
  const uid = await page.evaluate(async () => (await import('/mes-comptes/src/firebase.js')).auth.currentUser.uid)
  await logout(page)
  await page.getByRole('button', { name: 'Mot de passe oublié', exact: true }).click()
  await page.getByLabel('Adresse e-mail').fill(email)
  await page.getByRole('button', { name: 'Envoyer le lien' }).click()
  await expect(page.getByRole('status')).toContainText('Si un compte correspond')
  const { oobCodes } = await (await request.get('http://127.0.0.1:9099/emulator/v1/projects/demo-mes-comptes-v2/oobCodes')).json()
  const code = oobCodes.find(c => c.email === email && c.requestType === 'PASSWORD_RESET').oobCode
  await page.evaluate(async code => {
    const { confirmPasswordReset } = await import('/mes-comptes/node_modules/.vite/deps/firebase_auth.js')
    const { auth } = await import('/mes-comptes/src/firebase.js')
    await confirmPasswordReset(auth, code, 'mot de passe fictif Google')
  }, code)
  await page.getByRole('button', { name: 'Retour à la connexion' }).click()
  await page.getByLabel('Mot de passe', { exact: true }).fill('mot de passe fictif Google')
  await page.getByRole('button', { name: 'Se connecter', exact: true }).click()
  await expect(page.getByLabel('Passphrase', { exact: true })).toBeVisible()
  expect(await page.evaluate(async () => (await import('/mes-comptes/src/firebase.js')).auth.currentUser.uid)).toBe(uid)
})
